name: Core

on:
  push:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Set up NodeJS 18'
        uses: actions/setup-node@v4
        with:
          node-version: '18.17.1'

      - name: 'Install dependencies'
        run: npm install --workspaces

      - name: 'Run tests'
        run: npm run test --workspaces