name: Core/Web
run-name: Core/Web

on:
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Set up NodeJS 18'
        uses: actions/setup-node@v4
        with:
          node-version: '18.17.1'

      - name: 'Install npm dependencies'
        run: npm install --workspaces

      - name: 'Generate Prisma entities'
        run: npm run prisma:generate -w web  

      - name: 'Run core and web tests'
        run: npm run test --workspaces