name: Core

on:
  push:
    branches: [ master ]
    paths:
      - 'core/**'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Set up NodeJS 18'
        uses: actions/setup-node@v4
        with:
          node-version: '18.17.1'

      - name: 'Install dependencies'
        run: npm install

      - name: 'Run tests'
        run: npx jest --coverage

      - name: 'Run Stryker'
        run: npx stryker run

      - name: 'Run Cucumber'
        run: npm run test:cucumber

      - name: 'Upload Code Coverage'
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-reports
          path: ./coverage/**/*
          retention-days: 5

      - name: 'Upload Mutation Tests'
        uses: actions/upload-artifact@v4
        with:
          name: mutation-test-reports
          path: ./reports/**/*
          retention-days: 5